name: OWASP ZAP Scan

on:
  # Run on every push to main
  push:
    branches:
      - main
  # Run on every Pull Request targeting main
  pull_request:
    branches:
      - main
  # Keep manual trigger option
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the Web Application
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://owasp-insecure.netlify.app'
          fail_action: false

          # DISABLE individual issue creation to avoid spam
          allow_issue_writing: false

          # Name of the report file we want to generate
          cmd_options: '-r zap_report.html'

      - name: Upload HTML Report
        # This step grabs the report created above and saves it to GitHub
        if: always() # Run this even if ZAP finds bugs
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Security-Report
          path: zap_report.html
